/*
 IFT2935 - BASE DE DONNÉE
 Devoir#2 - ALGÈBRE RELATIONNEL & SQL
 Auteurs : @Nahomy Durand (20201414) & @Mariam Traoré (20114254)
 Remise : 5 mars 2024
 */

START TRANSACTION;

ALTER TABLE Poste ADD CONSTRAINT 
indIP_FK_Poste FOREIGN KEY (indIP) REFERENCES Segment(indIP);

ALTER TABLE Poste ADD CONSTRAINT 
typeLP_FK_Poste FOREIGN KEY (typePoste) REFERENCES Types(typeLP);

ALTER TABLE Poste ADD CONSTRAINT 
nSalle_FK FOREIGN KEY (nSalle) REFERENCES Salle(nSalle);

ALTER TABLE Installer ADD CONSTRAINT 
nPoste_FK FOREIGN KEY (nPoste) REFERENCES Poste(nPoste);

ALTER TABLE Installer ADD CONSTRAINT 
nLog_FK FOREIGN KEY (nLog) REFERENCES Logiciel(nLog);

-- SUPPRIMER LE TUPLE PROBLÉMATIQUE
DELETE FROM Logiciel WHERE typeLog = "BeOS";

ALTER TABLE Logiciel ADD CONSTRAINT 
typeLP_FK_Logiciel FOREIGN KEY (typeLog) REFERENCES Types(typeLP);

-- SUPPRIMER LES TUPLES PROBLÉMATIQUES
DELETE FROM SALLE WHERE nSalle = "s22" or nSalle = "s23";

ALTER TABLE Salle ADD CONSTRAINT 
indIP_FK_Salle FOREIGN KEY (indIP) REFERENCES Segment(indIP);

COMMIT;